version: '3'
services:

  prometheus:
    image: bitnami/prometheus
    ports: 
      - 9090:9090 
    networks:
      prometheus-network:
        ipv4_address: 172.18.0.3
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 1024M
    volumes:
      - /Users/borisgamanuk/Docker/course-project4/prometheus.yaml:/etc/prometheus/prometheus.yml
      - /Users/borisgamanuk/Docker/course-project4/alert-rules.yml:/etc/prometheus/alert-rules.yml
      - ./prometheus_data:/prometheus/

  node-exporter:
    image: bitnami/node-exporter
    ports: 
      - 9100:9100
    networks:
      prometheus-network:
        ipv4_address: 172.18.0.4
    depends_on:
     - nginx

# http://host.docker.internal:9090 - for connection to Data Sourses Prometheus
  grafana:
    image: grafana/grafana
    ports: 
      - 3000:3000
    networks:
      prometheus-network:
        ipv4_address: 172.18.0.6
    depends_on:
     - prometheus

  alertmanager:
    image: bitnami/alertmanager
    ports: 
      - 9093:9093
    networks:
      prometheus-network:
        ipv4_address: 172.18.0.5

  nginx:
    image: nginx
    ports: 
      - 80:80
      - 8080:8080
    networks:
      prometheus-network:
        ipv4_address: 172.18.0.10
    volumes:
     - /Users/borisgamanuk/Docker/course-project4/default.conf:/etc/nginx/conf.d/default.conf
     - /Users/borisgamanuk/Docker/course-project4/hosts:/etc/hosts
     - myapp:/var/log
    depends_on:
     - nginx-exporter 

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    ports: 
      - 9113:9113
    networks:
      prometheus-network:
        ipv4_address: 172.18.0.11
    command:
      - -nginx.scrape-uri
      - http://172.18.0.10:80/metrics


  postgres:
    image: postgres
    ports: 
      - 5432:5432
    networks:
      prometheus-network:
        ipv4_address: 172.18.0.12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    ports: 
      - 5050:80
    networks:
      prometheus-network:
        ipv4_address: 172.18.0.13
    environment:
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_DEFAULT_EMAIL: ic3peak7@mail.ru

  postgres-exporter:
    image: bitnami/postgres-exporter
    ports: 
      - 9187:9187
    networks:
      prometheus-network:
        ipv4_address: 172.18.0.14
    environment:
      DATA_SOURCE_NAME: postgresql://root:root@172.18.0.12:5432/postgres?sslmode=disable
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
#docker volume create --name=myapp
volumes:
  myapp:
    external: true

networks:
  prometheus-network:
    ipam:
      config:
        - subnet: 172.18.0.0/16

            